### ISSUE TITLE
KeyError 50

### ISSUE THREAD

**Issue by rebeelouise** [dayzerodx/counterr#5]
Traceback (most recent call last):
  File "/home/hlrpenri/anaconda3/bin/counterr", line 12, in <module>
    sys.exit(main())
  File "/home/hlrpenri/anaconda3/lib/python3.7/site-packages/counterr/counterr.py", line 128, in main
    qs, nums_match_q, nums_sub_q, nums_ins_q, nums_err_q, nums_tot_q = phredQ_vs_error(alns, verbose=verbose)
  File "/home/hlrpenri/anaconda3/lib/python3.7/site-packages/counterr/counters.py", line 390, in phredQ_vs_error
    Q_dict[q][cig[i]] += 1
KeyError: 50

Hi - I'm a bit of a coding noob, I've come across this error - half of the figures have been generated.
Could you help me resolve this?

**Comment by rebeelouise** [comment]
In additon, the PDF file is corrupted and I cannot view it...

**Comment by BjoernUsadel** [comment]
Very late but if someone else has this issue 
in counters.py 
change
def phredQ_vs_error(alns, max_Q=50, verbose=False):
to e.g. 
def phredQ_vs_error(alns, max_Q=65, verbose=False):

the corrupt pdf is because the script doesn't run through

PS master has this at 100 so should work
